#+TITLE: Replication Material For "Short-term Planning, Monetary Policy, and Macroeconomic Persistence"

The code in this replication package estimates the models and
constructs the figures and table from Gust, Herbst, and Lopez-Salido
(AEJ: Macro, 202x) using Fortran and Python.  

** Data
   
   All of the data is publicly available. 
   
*** Data Availability and Provenance Statements

    Here is a description of the data used in the estimation of the models.

    1. *Real Gross Domestic Product.* This is part of National Income
       and Product Accounts (NIPA), released by the Bureau of Economic
       Analysis.  (FRED mnenomic ~GDPC1~.)

    2. *Civilian Noninstitutional Population.* This is part of the
       Employment Situation report, released by the Bureau of Labor
       Statistics. (FRED mnenomic ~CNP16OV~.)

    3. *GDP Deflator.* This is part of National Income
       and Product Accounts (NIPA), released by the Bureau of Economic
       Analysis.  (FRED mnenomic ~GDPDEF~.)

    4. *Federal Funds Rate.* This is part of the H.15 Selected
       Interest Rates report, released by the Board of Governors of
       the Federal Reserve System.  (FRED mnenomic ~FEDFUNDS~.)

       
    Here is a description of additional data used in plotting. 

    1. *Potential GDP.* This is part of the Budget and Economic
       Outlook report, released by the Congressional Budget
       Office. (FRED mnenomic ~GDPPOT~.)

    2. *Recession Indicator.* This is part of the Recession Indicator
       Series, released by the Federal Reserve Bank of St. Louis.
       (FRED mnenomic ~USRECQ~.)

    3. *Long-term Inflation Expectations.* This is part of the
       historical FRB/US database, released by the Board of Governors
       of the Federal Reserve System.  The data can be obtained 
       [[https://www.federalreserve.gov/econres/us-models-package.htm][here]].  The variable name is ~PTR~. 

*** Statement about Rights

    We certify that we have legitimate access to and permission to use
    the data used in this manuscript.

*** License for Data

    All the data except the "Recession Indicator" are from
    U.S. government agencies are "works of the United States
    government" under the Copyright Act.  As such, these data are
    ineligible for copyright protection and in the public domain.
    

** Computation

*** Software Requirements

- Linux-based operating system. 
- Conda package and environment management system. 
  - The file ~env.yaml~ contains the details of the python3+mpif90 environment to run all of the code.  See /Instructions to Replicators/ step 2 to install this environment. 


*** Memory and Runtime Requirements

**** Summary

Approximate time needed to reproduce the analyses on a standard (2020) desktop machine:

- [ ] <10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] 8-24 hours
- [ ] 1-3 days
- [X] 3-14 days
- [ ] > 14 days
- [ ] Not feasible to run on a desktop machine, as described below.

**** Details

Portions of the code were last run on a **32-core Intel server with 1024 GB of RAM, 12 TB of fast local storage**. Computation took 734 hours. 

**** Description of code
     

*** License for Code

    Code written by the co-authors are each a "work of the United States government" under the Copyright Act.  As such, these codes are ineligible for copyright protection and in the public domain.

** Instructions to Replicators

  1. Install [[https://docs.conda.io/en/latest/][Conda]].
  2. From a shell prompt, create the necessary python environment, using:
     #+begin_src sh
     user@computer:short-term-planning-replication$ conda env create --file env.yaml
     #+end_src 
  3. Activate the environment with:
     #+begin_src sh
     user@computer:short-term-planning-replication$ source activate short-term-planning-replication
     #+end_src 
  4. /(Optional.)/ Download the data from FRED:
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ python 01-construct-estimation-data.py
     #+end_src      
  5. Create the fortran models with:
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ python 02-construct-fortran-models.py
     #+end_src      
  6. Estimate all the models with: 
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ ./estimate-all-models.sh
     #+end_src      
     /Note/: this can take quite a long time! See the details below to for how to estimate individual models.
  7. Construct the tables and figures.
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ ./construct-all-tables-and-figures.sh
     #+end_src           
     /Note/: this can take quite a long time! See the details below to for how to create individual tables and figures.  


**** Details


*** List of tables and programs

The provided code reproduces all numbers provided in text in the
paper.  Please be aware because that numbers generated in the
replication can differ from the published version slightly because of
the numerical standard error associated with the sequential Monte
Carlo algorithm. 

|----------------+-----------------------------------------------+-------------+---------------------------------------|
| Figure/Table # | Program                                       | Line Number | Output File                           |
|----------------+-----------------------------------------------+-------------+---------------------------------------|
| Figure 1       | 04-fig-impulse-response-disinflation-shock.py |             | disinflation_shock.pdf                |
| Table 3        | 05-tab-posterior.py                           |             | main-posterior-table.tex              |
| Figure 2       | 06-fig-joint-posterior.py                     |             | rho_gamma_scatter.pdf                 |
| Figure 3       | 07-fig-difference-log-mdd-time.py             |             |                                       |
| Figure 4       | 08-fig-impulse-response-monetary-shock.py     |             | woodford_terminal_irf_epsi_shaded.pdf |
| Figure 5       | 09-fig-trend-cycle-decomposition.py           |          35 | woodford_terminal_smooth_shaded.pdf   |
| Figure 6       | 10-fig-trend-cycle-decomposition.py           |          59 | woodford_terminal_smooth_shaded_i.pdf |
| Figure 7       | 11-fig-trend-cycle-decomposition.py           |          72 | woodford_terminal_y_level.pdf         |
| Figure 8       | 12-fig-estimated-shocks.py                    |             |                                       |
| Figure 9       |                                               |             | shock_decomposition.pdf               |
|----------------+-----------------------------------------------+-------------+---------------------------------------|


** References




** Acknowledgements


