#+TITLE: Replication Material For "Short-term Planning, Monetary Policy, and Macroeconomic Persistence"

The code in this replication package estimates the models and
constructs the figures and table from Gust, Herbst, and Lopez-Salido
(AEJ: Macro, 202x) using Fortran and Python.  

** Data
*** Data Availability and Provenance Statements

> NOTE: DAS do not replace Data Citations (see [Guidance](Data_citation_guidance.md)). Rather, they augment them. Depending on journal requirements and to some extent stylistic considerations, data citations should appear in the main article, in an appendix, or in the README. However, data citations only provide information **where** to find the data, not **how to access** that data. Thus, DAS augment data citations by going into additional detail that allow a researcher to assess cost, complexity, and availability over time of the data used by the original author.

*** Statement about Rights

    We certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript. 


*** License for Data

> INSTRUCTIONS: Most data repositories provide for a default license, but do not impose a specific license. Authors should actively select a license. This should be provided in a LICENSE.txt file, separately from the README, possibly combined with the license for any code. Some data may be subject to inherited license requirements, i.e., the data provider may allow for redistribution only if the data is licensed under specific rules - authors should check with their data providers. For instance, a data use license might require that users - the current author, but also any subsequent users - cite the data provider. Licensing can be complex. Some non-legal guidance may be found [here](https://social-science-data-editors.github.io/guidance/Licensing_guidance.html).

The code is licensed under a Creative Commons/CC-BY-NC/CC0 license. See [LICENSE.txt](LICENSE.txt) for details.


*** Summary of Availability

- [X] All data **are** publicly available.
- [ ] Some data **cannot be made** publicly available.
- [ ] **No data can be made** publicly available.


*** Data Used in Estimation

    

** Computation

*** Software Requirements

- Linux-based operating system. 
- Conda package and environment management system. 
  - The file ~env.yaml~ contains the details of the python3+mpif90 environment to run all of the code.  See /Instructions to Replicators/ step 2 to install this environment. 


*** Memory and Runtime Requirements

**** Summary

Approximate time needed to reproduce the analyses on a standard (2020) desktop machine:

- [ ] <10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] 8-24 hours
- [ ] 1-3 days
- [X] 3-14 days
- [ ] > 14 days
- [ ] Not feasible to run on a desktop machine, as described below.

**** Details

Portions of the code were last run on a **32-core Intel server with 1024 GB of RAM, 12 TB of fast local storage**. Computation took 734 hours. 

**** Description of code
     

*** License for Code

    See LICENSE.txt 

** Instructions to Replicators

  1. Install [[https://docs.conda.io/en/latest/][Conda]].
  2. From a shell prompt, create the necessary python environment, using:
     #+begin_src sh
     user@computer:short-term-planning-replication$ conda env create --file env.yaml
     #+end_src 
  3. Activate the environment with:
     #+begin_src sh
     user@computer:short-term-planning-replication$ source activate short-term-planning-replication
     #+end_src 
  4. /(Optional.)/ Download the data from FRED:
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ python 01-construct-estimation-data.py
     #+end_src      
  5. Create the fortran models with:
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ python 02-construct-fortran-models.py
     #+end_src      
  6. Estimate all the models with: 
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ ./estimate-all-models.sh
     #+end_src      
     /Note/: this can take quite a long time! See the details below to for how to estimate individual models.
  7. Construct the tables and figures.
     #+begin_src sh
     (short-term-planning-replication) user@computer:short-term-planning-replication$ ./construct-all-tables-and-figures.sh
     #+end_src           
     /Note/: this can take quite a long time! See the details below to for how to create individual tables and figures.  


**** Details


*** List of tables and programs

The provided code reproduces all numbers provided in text in the
paper.  Please be aware because that numbers generated in the
replication can differ from the published version slightly because of
the numerical standard error associated with the sequential Monte
Carlo algorithm. 

|----------------+---------------------------------------------------+-------------+-------------+------|
| Figure/Table # | Program                                           | Line Number | Output File | Note |
|----------------+---------------------------------------------------+-------------+-------------+------|
| Figure 1       | 04-fig-impulse-response-disinflation-shock.py     |             |             |      |
| Table 3        | 05-tab-posterior.py                               |             |             |      |
| Figure 2       | 06-fig-joint-posterior.py                         |             |             |      |
| Figure 3       | 07-fig-difference-log-mdd-time.py                 |             |             |      |
| Figure 4       | 08-fig-impulse-response-monetary-shock.py         |             |             |      |
| Figure 5       | 09-fig-trend-cycle-decomposition-inflation.py     |             |             |      |
| Figure 6       | 10-fig-trend-cycle-decomposition-interest-rate.py |             |             |      |
| Figure 7       | 11-fig-trend-cycle-decomposition-output.py        |             |             |      |
| Figure 8       | 12-fig-estimated-shocks.py                        |             |             |      |
|----------------+---------------------------------------------------+-------------+-------------+------|


** References




** Acknowledgements


