python 03-estimate-baseline-models.py --model canonical_NK --nprocs 4
python 03-estimate-baseline-models.py --model trends --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_gamma --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar --nprocs 4
python 03-estimate-baseline-models.py --model angeletos_lian --nprocs 4
python 03-estimate-baseline-models.py --model habits --nprocs 4
python 03-estimate-baseline-models.py --model habits_lampi --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar_k0 --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar_k1 --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar_k2 --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar_k3 --nprocs 4
python 03-estimate-baseline-models.py --model finite_horizon_phibar_k4 --nprocs 4
